services:
  relayer:
    build:
      context: .
      dockerfile: Dockerfile
      target: relayer
    ports:
      - 3111:3111
      # - 3112:3112
    environment:
      - KARURA_ETH_RPC=https://eth-rpc-karura-testnet.aca-staging.network
      - KARURA_PRIVATE_KEY=efb03e3f4fd8b3d7f9b14de6c6fb95044e2321d6bcb9dfe287ba987920254044

      - KARURA_ETH_RPC=https://eth-rpc-acala-testnet.aca-staging.network
      - ACALA_PRIVATE_KEY=efb03e3f4fd8b3d7f9b14de6c6fb95044e2321d6bcb9dfe287ba987920254044

      - PORT=3111
      - TESTNET_MODE=1
    restart: always
