services:
  # relayer:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: relayer
  #   ports:
  #     - 3111:3111
  #   environment:
  #     - KARURA_RPC_URL_WS=wss://karura-dev.aca-dev.network/eth/ws
  #     - KARURA_RPC_URL_HTTP=https://karura-dev.aca-dev.network/eth/http
  #     - KARURA_SUBSTRATE_NODE_URL=wss://karura-dev.aca-dev.network/rpc/ws
  #     - KARURA_PRIVATE_KEY=efb03e3f4fd8b3d7f9b14de6c6fb95044e2321d6bcb9dfe287ba987920254044
  #     - KARURA_TOKEN_BRIDGE_ADDRESS=0xd11De1f930eA1F7Dd0290Fe3a2e35b9C91AEFb37

  #     - ACALA_RPC_URL_WS=wss://acala-dev.aca-dev.network/eth/ws
  #     - ACALA_RPC_URL_HTTP=https://acala-dev.aca-dev.network/eth/http
  #     - ACALA_SUBSTRATE_NODE_URL=wss://acala-dev.aca-dev.network/rpc/ws
  #     - ACALA_PRIVATE_KEY=efb03e3f4fd8b3d7f9b14de6c6fb95044e2321d6bcb9dfe287ba987920254044
  #     - ACALA_TOKEN_BRIDGE_ADDRESS=0xebA00cbe08992EdD08ed7793E07ad6063c807004

  #     - PORT=3111
  #     - TESTNET_MODE=0
  #   restart: always
  relayer-karura-mainnet:
    image: acala/relayer:6abf436
    ports:
      - 3111:3111
    environment:
      - KARURA_RPC_URL_WS=wss://eth-rpc-karura.aca-api.network/ws
      - KARURA_RPC_URL_HTTP=https://eth-rpc-karura.aca-api.network
      - KARURA_SUBSTRATE_NODE_URL=wss://acala-karura-eu-1.bdnodes.net:8443/parachain?auth=4VFR_UEvc8mUAd58z11nSRqp-EBZcqPl14j_MgEm-4E
      - KARURA_PRIVATE_KEY=efb03e3f4fd8b3d7f9b14de6c6fb95044e2321d6bcb9dfe287ba987920254044
      - KARURA_TOKEN_BRIDGE_ADDRESS=0xae9d7fe007b3327AA64A32824Aaac52C42a6E624

      - PORT=3111
      - TESTNET_MODE=0
    restart: always
