version: '3.8'

services:
  node:
    container_name: node
    image: oven/bun:1
    working_dir: /app
    volumes:
      - ./src/__tests__/configs/acala.yml:/app/acala.yml
    command:
      bunx @acala-network/chopsticks@latest -c /app/acala.yml
    ports:
      - 8000:8000
    healthcheck:
      test: "exit 0"
      # FIXME: does not seem to work
      # test: "curl --fail -X POST -H \"Content-Type: application/json\" http://localhost:8000 -d \"{\"id\": 1, \"jsonrpc\": \"2.0\", \"method\": \"system_health\", \"params\": []}\" || exit 1"
      interval: 2s
      retries: 100
      start_period: 10s

  eth-rpc:
    container_name: eth-rpc
    image: acala/eth-rpc-adapter:2.8.7
    restart: always
    depends_on:
      node:
        condition: service_healthy
    ports:
      - 8545:8545
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - ENDPOINT_URL=ws://node:8000
    command: yarn start