services:
  relayer:
    build:
      context: .
      dockerfile: Dockerfile
      target: relayer
    ports:
      - 3111:3111
    restart: always
    environment:
      KARURA_ENDPOINT_URL: ws://157.245.62.53:9944
