/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface BaseRouterInterface extends utils.Interface {
  functions: {
    "fees()": FunctionFragment;
    "route(address,address)": FunctionFragment;
    "routeNoFee(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "fees" | "route" | "routeNoFee"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "fees", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "route",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "routeNoFee",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "fees", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "route", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "routeNoFee", data: BytesLike): Result;

  events: {
    "RouterCreated(address)": EventFragment;
    "RouterDestroyed(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RouterCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RouterDestroyed"): EventFragment;
}

export interface RouterCreatedEventObject {
  addr: string;
}
export type RouterCreatedEvent = TypedEvent<[string], RouterCreatedEventObject>;

export type RouterCreatedEventFilter = TypedEventFilter<RouterCreatedEvent>;

export interface RouterDestroyedEventObject {
  addr: string;
}
export type RouterDestroyedEvent = TypedEvent<
  [string],
  RouterDestroyedEventObject
>;

export type RouterDestroyedEventFilter = TypedEventFilter<RouterDestroyedEvent>;

export interface BaseRouter extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BaseRouterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    fees(overrides?: CallOverrides): Promise<[string]>;

    route(
      token: PromiseOrValue<string>,
      relayer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    routeNoFee(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  fees(overrides?: CallOverrides): Promise<string>;

  route(
    token: PromiseOrValue<string>,
    relayer: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  routeNoFee(
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    fees(overrides?: CallOverrides): Promise<string>;

    route(
      token: PromiseOrValue<string>,
      relayer: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    routeNoFee(
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "RouterCreated(address)"(
      addr?: PromiseOrValue<string> | null
    ): RouterCreatedEventFilter;
    RouterCreated(
      addr?: PromiseOrValue<string> | null
    ): RouterCreatedEventFilter;

    "RouterDestroyed(address)"(
      addr?: PromiseOrValue<string> | null
    ): RouterDestroyedEventFilter;
    RouterDestroyed(
      addr?: PromiseOrValue<string> | null
    ): RouterDestroyedEventFilter;
  };

  estimateGas: {
    fees(overrides?: CallOverrides): Promise<BigNumber>;

    route(
      token: PromiseOrValue<string>,
      relayer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    routeNoFee(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    fees(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    route(
      token: PromiseOrValue<string>,
      relayer: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    routeNoFee(
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
